import { describe, test, expect } from "vitest";
import React from "react";
import { render } from "@testing-library/react";
import { ChatMessage } from "#/components/features/chat/chat-message";

describe("ChatMessage sanitization", () => {
  test("chat message shows sanitized mention, not clickable", () => {
    render(<ChatMessage type="agent" message="Ping @openhands please" />);
    const html = document.body.innerHTML;
    // No links generated by react-markdown for our sanitized text
    expect(document.querySelectorAll("a").length).toBe(0);
    expect(html).toContain("@\u200Dopenhands");
  });

  test("chat message preserves code blocks", () => {
    render(
      <ChatMessage
        type="agent"
        message="Code: `@openhands` and text: @openhands"
      />,
    );
    const html = document.body.innerHTML;
    // Should have both sanitized and unsanitized versions
    expect(html).toContain("@openhands"); // in code
    expect(html).toContain("@\u200Dopenhands"); // in text
  });

  test("user messages are not affected by sanitization", () => {
    render(<ChatMessage type="user" message="Hello @openhands" />);
    const html = document.body.innerHTML;
    // User messages should still be sanitized for consistency
    expect(html).toContain("@\u200Dopenhands");
  });
});
