"""Sync DB with Models.

Revision ID: 8f703d51077a
Revises:
Create Date: 2025-10-04 09:13:01.062006
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f703d51077a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('v1_app_conversation_info',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.Column('selected_repository', sa.String(), nullable=True),
    sa.Column('selected_branch', sa.String(), nullable=True),
    sa.Column('git_provider', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('trigger', sa.String(), nullable=True),
    sa.Column('pr_number', sa.JSON(), nullable=True),
    sa.Column('llm_model', sa.String(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('sandbox_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_v1_app_conversation_info_created_at'), 'v1_app_conversation_info', ['created_at'], unique=False)
    op.create_index(op.f('ix_v1_app_conversation_info_created_by_user_id'), 'v1_app_conversation_info', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_v1_app_conversation_info_sandbox_id'), 'v1_app_conversation_info', ['sandbox_id'], unique=False)
    op.create_index(op.f('ix_v1_app_conversation_info_updated_at'), 'v1_app_conversation_info', ['updated_at'], unique=False)
    op.create_table('v1_app_conversation_start_task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('app_conversation_id', sa.UUID(), nullable=True),
    sa.Column('sandbox_id', sa.String(), nullable=True),
    sa.Column('agent_server_url', sa.String(), nullable=True),
    sa.Column('request', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_v1_app_conversation_start_task_created_at'), 'v1_app_conversation_start_task', ['created_at'], unique=False)
    op.create_index(op.f('ix_v1_app_conversation_start_task_created_by_user_id'), 'v1_app_conversation_start_task', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_v1_app_conversation_start_task_updated_at'), 'v1_app_conversation_start_task', ['updated_at'], unique=False)
    op.create_table('v1_event_callback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('processor', sa.JSON(), nullable=True),
    sa.Column('event_kind', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_v1_event_callback_created_at'), 'v1_event_callback', ['created_at'], unique=False)
    op.create_table('v1_event_callback_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('event_callback_id', sa.UUID(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_v1_event_callback_result_conversation_id'), 'v1_event_callback_result', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_v1_event_callback_result_created_at'), 'v1_event_callback_result', ['created_at'], unique=False)
    op.create_index(op.f('ix_v1_event_callback_result_event_callback_id'), 'v1_event_callback_result', ['event_callback_id'], unique=False)
    op.create_index(op.f('ix_v1_event_callback_result_event_id'), 'v1_event_callback_result', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_v1_event_callback_result_event_id'), table_name='v1_event_callback_result')
    op.drop_index(op.f('ix_v1_event_callback_result_event_callback_id'), table_name='v1_event_callback_result')
    op.drop_index(op.f('ix_v1_event_callback_result_created_at'), table_name='v1_event_callback_result')
    op.drop_index(op.f('ix_v1_event_callback_result_conversation_id'), table_name='v1_event_callback_result')
    op.drop_table('v1_event_callback_result')
    op.drop_index(op.f('ix_v1_event_callback_created_at'), table_name='v1_event_callback')
    op.drop_table('v1_event_callback')
    op.drop_index(op.f('ix_v1_app_conversation_start_task_updated_at'), table_name='v1_app_conversation_start_task')
    op.drop_index(op.f('ix_v1_app_conversation_start_task_created_by_user_id'), table_name='v1_app_conversation_start_task')
    op.drop_index(op.f('ix_v1_app_conversation_start_task_created_at'), table_name='v1_app_conversation_start_task')
    op.drop_table('v1_app_conversation_start_task')
    op.drop_index(op.f('ix_v1_app_conversation_info_updated_at'), table_name='v1_app_conversation_info')
    op.drop_index(op.f('ix_v1_app_conversation_info_sandbox_id'), table_name='v1_app_conversation_info')
    op.drop_index(op.f('ix_v1_app_conversation_info_created_by_user_id'), table_name='v1_app_conversation_info')
    op.drop_index(op.f('ix_v1_app_conversation_info_created_at'), table_name='v1_app_conversation_info')
    op.drop_table('v1_app_conversation_info')
    # ### end Alembic commands ###
