export type RuntimeStatus =
  | "STATUS$STOPPED"
  | "STATUS$BUILDING_RUNTIME"
  | "STATUS$STARTING_RUNTIME"
  | "STATUS$RUNTIME_STARTED"
  | "STATUS$SETTING_UP_WORKSPACE"
  | "STATUS$SETTING_UP_GIT_HOOKS"
  | "STATUS$READY";
