from unittest.mock import MagicMock, patch

from openhands.integrations.service_types import ProviderType
from openhands.resolver.interfaces.bitbucket import BitbucketIssueHandler
from openhands.resolver.interfaces.issue import Issue
from openhands.resolver.send_pull_request import send_pull_request


@patch('openhands.resolver.send_pull_request.BitbucketIssueHandler')
def test_send_pull_request_bitbucket(mock_bitbucket_handler):
    # Mock the BitbucketIssueHandler instance
    mock_instance = MagicMock(spec=BitbucketIssueHandler)
    mock_instance.create_pr.return_value = (
        'https://bitbucket.org/test-workspace/test-repo/pull-requests/123'
    )
    mock_bitbucket_handler.return_value = mock_instance

    # Create a mock Issue
    mock_issue = Issue(
        number=123,
        title='Test Issue',
        owner='test-workspace',
        repo='test-repo',
        body='Test body',
        created_at='2023-01-01T00:00:00Z',
        updated_at='2023-01-01T00:00:00Z',
        closed_at=None,
        head_branch='feature-branch',
        thread_ids=None,
    )

    # Call send_pull_request
    result = send_pull_request(
        issue=mock_issue,
        token='test-token',
        username=None,
        platform=ProviderType.BITBUCKET,
        patch_dir='/tmp/repo',
        pr_type='ready',
        pr_title='Test PR',
        target_branch='main',
    )

    # Verify the result
    assert result == 'https://bitbucket.org/test-workspace/test-repo/pull-requests/123'

    # Verify the handler was created correctly
    mock_bitbucket_handler.assert_called_once_with(
        'test-workspace',
        'test-repo',
        'test-token',
        None,
        'bitbucket.org',
    )

    # Verify create_pr was called correctly with the expected body
    expected_body = 'This pull request fixes #123.\n\nAutomatic fix generated by [OpenHands](https://github.com/All-Hands-AI/OpenHands/) 🙌'
    mock_instance.create_pr.assert_called_once_with(
        title='Test PR',
        body=expected_body,
        head='feature-branch',
        base='main',
    )
